name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ramsey/composer-install@v2 # or alternative dependency management
    - uses: dingo-d/phpstan-wp-action@v2
